version: '3.1'     

services: 
   mongo:
     container_name:  mongo_server1 
     image: mongo:latest
     ports: 
       - 27017:27017
   golang-v:
      container_name: app1
      image: golang-v:1.0
      ports:
        - 8080:8080
      depends_on:
        - mongo
